### ISSUE TITLE
Component presente with trues types

### ISSUE THREAD

**Issue by mrtvrgn** [Comcast/blueprint#13]
Currently any component presenter provides generic type as ComponentView<*> and ComponentModel. However, it should provide true type without casting seemly at present. This will not only decrease implementation speed but also ignore extra casting on runtime. 
We also need to provide presenters that doesn't need model should only aquire view not anonymous model when they present..

**Comment by dapp** [comment]
addressed in https://github.com/Comcast/blueprint/pull/14 

closing
